name: Save RSI History

on:
  schedule:
    - cron: "*/10 20-23 * * 1-5"
  workflow_dispatch: {}

jobs:
  save-rsi:
    runs-on: ubuntu-latest
    steps:
      - name: Call RSI Save API
        run: |
          curl -X POST "${{ secrets.RENDER_CRON_URL }}/cron/save?secret=${{ secrets.CRON_SECRET }}"
